// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © khai

//@version=5
indicator("Selected Percentage from Current Price", overlay=true)

// Define the percentage value
breakevenPercent = input.float(0.8, title="Breakeven Percent", minval=0, maxval=100)
dte = input.int(3,title = "Day To Expiry")

// Get the prices
currentPrice = (close)
dtePrice=(close[dte])

// Calculate price level
breakevenPrice = close * (1 - breakevenPercent / 100) 
previousBreakPrice = close[dte] * (1 - breakevenPercent / 100) 

upTrend=close[1]<close
downTrend=close[1]>close
//condition for fail breakeven
failBreakeven=previousBreakPrice>close

plot(previousBreakPrice, title="Breakeven Test Line", color=color.purple, linewidth=1)
plot(breakevenPrice, title="Breakeven Line", color=color.yellow, linewidth=1)
plotshape(failBreakeven,style = shape.triangledown,location = location.belowbar,color=color.red, title="Failed Breakeven")
//plotshape(upTrend,style=shape.triangleup,location=location.abovebar, color=color.green)


//Function to Calculate Zero lag EMA
zema(src,len) =>
    lag = len>1 ? (len - 1)/2 : 0
    ema_data = (src + (src - nz(src[lag])))
    result = ta.ema(ema_data, len)
    result

srcClose = request.security(ticker.heikinashi(syminfo.tickerid),timeframe.period,close)
length = input.int(20, minval=2,title="Zero Lag EMA (DOTS) Length")
zlema = zema(srcClose, length)
col =  zlema > zlema[1] ? color.new(#00FF00,90) : color.new(#FF0000,90)



// Draw the DOT no lag MA and colour background to make it easier to see.
plot(zlema,color=col, linewidth=1, title="HA Zero Lag EMA line")
bgcolor(col,title="HA Zero Lag EMA Background")


 